### ISSUE TITLE
error on exporting Word files 

### ISSUE THREAD

**Issue by xfanwu** [DaoCloud/DaoCloud-docs#2413]
I encountered an error when trying to export a Word document based on this [document](https://github.com/DaoCloud/DaoCloud-docs/blob/main/scripts/generate_pdf.md).

`python scripts/md2doc-v2.py docs/en/docs/dce/
Traceback (most recent call last):
  File "/Users/xw/Code/DaoCloud/DaoCloud-docs/scripts/md2doc-v2.py", line 7, in <module>
    from docx import Document
ModuleNotFoundError: No module named 'docx'`

And I install "docx" via `pip install`, but I got another missing module that I can't install from pip.

`python scripts/md2doc-v2.py docs/en/docs/dce/
Traceback (most recent call last):
  File "/Users/xw/Code/DaoCloud/DaoCloud-docs/scripts/md2doc-v2.py", line 7, in <module>
    from docx import Document
  File "/Users/xw/.pyenv/versions/3.10.6/lib/python3.10/site-packages/docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'`

**Comment by xfanwu** [comment]
The problem is fixed, there are dependencies need to be installed:

1. `pip install python-docx`

2. `brew install pandoc`

Hope it is helpful!

**Comment by windsonsea** [comment]
Thank you very much. Will add this tip into the Word-file instructions.
